name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "ci_cd" ]
  pull_request:
    branches: [ "main", "ci_cd" ]

env:
  IMAGE_NAME: student_service
  VALIDATE_JAVA: true
  DEFAULT_BRANCH: main
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  AWS_REGION: us-east-1                  # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: test_repo_for_ci_cd           # set this to your Amazon ECR repository name
  ECS_SERVICE: deploy_test-service-i2vnfjcz                 # set this to your Amazon ECS service name
  ECS_CLUSTER: frugal-hamster-i5wlfx                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: .aws/deploy_test-revision1.json # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: ci-cd_test           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

jobs:
  # JOB 1: Test the code
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # probably don't need this but I wanted to have it as a test
      - name: Run Super-Linter
        uses: github/super-linter@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: ${{ env.AWS_REGION }}